### PR TITLE
Initial plugin draft

### LINKED ISSUE #2: add some initial docs/howtos

### LINKED ISSUE #3: add apache2 license

### PR DESCRIPTION
**Pull request by arknable**
Implemented features:

1. Run
2. Run with configuration
3. Run opened file
2. Stop 
4. Build
5. Start instance
6. Stop instance

### CODE REVIEW

**Comment by arknable** [comment]
Run and stop action runs pretty well. But I think we need to notify user when an application is running or exited via balloon notification. Currently I don't see the notification popped up ... so I am still troubleshoot this one.

**Comment by eyberg** [comment]
I think it's fine to leave the balloon notifications as separate work - we can put that into a pr - we're just looking for basic integration today - much the same way vscode plugin works

**Comment by arknable** [comment]
@eyberg ok.

**Comment by arknable** [comment]
Notification balloon will only be displayed if a project opened, so if none does we will just log into Event Log

**Review by eyberg — APPROVED** [review]

**Comment by arknable** [comment]
@eyberg I have added one commit: https://github.com/nanovms/ops-intellij/pull/1/commits/e39c18792978e989e1f8b18fdcc3cd1d7529da30

**Comment by arknable** [comment]
@eyberg commits squashed

**Comment by eyberg** [comment]
@arknable let's go ahead and merge this - we can do any other work in a diff pr

**Pull request merged**
